[[language]]
name = "python"
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
black.enabled = true
flake8.enabled = true
mypy.enabled = true
isort.enabled = true
rope.enabled = true
ruff.enabled = true

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "bash", args = ["-c", "dprint fmt --config ~/.config/dprint/dprint.json --stdin md"] }

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "c"
auto-format = true
